### ISSUE TITLE
오타 제보 p388, p568, p587, p599

### ISSUE THREAD

**Issue by jongrom2** [yjiq150/coronaboard-book-code#2]
안녕하세요. 
책 완독 후 오타 제보입니다.

- p388
오타라기 보다는 ds is not defined 에러 발생에 따른 수정사항입니다.
youtube.js 코드에서 아래와 같이 수정하면 정상 동작합니다.
as-is : return ds;
to-be : return text;

- p568, p599
책 내용 중 windows -> window로 수정 필요합니다.
(깃헙 소스코드에는 window로 되어있어 수정 불필요합니다.)

- p587
상단 그림에 동그라미 2개 모두 '1번'으로 표기되었습니다. '보고서모음수정' 버튼을 '2번'으로 표기되도록 수정 필요합니다.

감사합니다.

**Comment by yjiq150** [comment]
제보 감사합니다. 이부분도 정오표에 반영했습니다. https://docs.google.com/spreadsheets/d/1vYQMB2IqhlgCrSKaHJFDoQsAQlJQpUGPY1_d7-qVong/edit#gid=0
