### ISSUE TITLE
findAllGlobalStat 함수 내용 누락 제보(p.306)

### ISSUE THREAD

**Issue by jongrom2** [yjiq150/coronaboard-book-code#3]
p.306의 global-updater.js에서 apiClient.findAllGlobalStat() 함수를 사용하는데, 책에서 api-client.js안의 findAllGlobalStat()함수를 작성하는 내용이 없습니다.(열심히 찾아봤는데 제가 못 찾은 것일 수도 있습니다;)

깃허브 소스코드의 api-client.js안에는 findAllGlobalStat 함수가 작성되어있어 해당 코드 참고하여 진행 가능합니다.

이후에 책 읽으시는 분들 참고하시면 도움이 될 것 같아 남깁니다.

**Comment by yjiq150** [comment]
코드 내용을 책으로 옮기면서 누락된것같네요. 제보감사합니다!

전체 공개로 책 정오표를 관리중인데 이쪽에 반영해두었습니다.
https://docs.google.com/spreadsheets/d/1vYQMB2IqhlgCrSKaHJFDoQsAQlJQpUGPY1_d7-qVong/edit#gid=0
