### ISSUE TITLE
[문의] 국가별 현황 필터 동작방식

### ISSUE THREAD

**Issue by ncrash** [yjiq150/coronaboard-book-code#4]
안녕하세요

우선 좋은 책을 집필해주셔서 감사합니다. 여러모로 도움이 많이 됐습니다.
책을 보며 예제코드 실습 중에 현재 코로나보드 사이트와 비교하다 차이점을 발견하고 구현방식이 궁금해져 문의를 남깁니다

국가별 현황 필터의 구현방식이 궁금합니다.
나름 구현방식을 알아보고자 여러시도들을 해봤으나 구현방식을 찾지 못했네요
react-select의 isMulti 옵션과 다른 컴포넌트들을 간략히 훑어보았으나 ux에서 상당히 거리가 있네요 🤣

![2024-06-10 at 16 12](https://github.com/yjiq150/coronaboard-book-code/assets/153414/b2728c1b-a2c8-423b-abc8-3b700c90a85e)

![2024-06-10 at 16 14](https://github.com/yjiq150/coronaboard-book-code/assets/153414/31bafecd-60b3-4a86-821c-4ad7377bc0d8)

**Comment by yjiq150** [comment]
안녕하세요 권영재입니다.

coronaboard.kr 웹사이트의 경우 bootstrap + jquery + webpack 방식으로 만들어져있습니다. 문의 주신 컴포넌트는 [bootstrap-select](https://github.com/snapappointments/bootstrap-select) 를 사용하고있습니다.

jquery가 오래된 기술이지만 간단한 싱글페이지 웹사이트를 만들때는 react보다 생산성이 더 좋은 편이라 실제 프로젝트를 진행할때는 jquery를 사용해서 작업했었습니다.

다만 jquery같은 경우 독자들에게 인기있는 주제가 아니다보니 책 집필 용으로 예제 프로젝트를 만들기 위해서 react를 사용하는 gatsby 프레임워크를 선택해서 별도로 작업을 했습니다.

책 예제 내용과 실제 웹사이트를 자세히 비교도 해봐주시고, 관심 가져주셔서 감사합니다!

**Comment by ncrash** [comment]
답변 주신 내용을 검토 및 적용해보느라 답이 늦었습니다 :)
가이드 주신 방법으로 적용을 해보니 손쉽게 적용이 가능하네요. 

친절한 답변 감사드립니다!
